google.client.id=977963570920-mtgqrosdib14ulgd185mkbcgk7gi4cpf.apps.googleusercontent.com
google.client.secret=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
api.base.url=https://api.dangpham.id.vn
ws.nestjs.url=https://ws.dangpham.id.vn/ws-game
ws.go.url=wss://ws-go.dangpham.id.vn/ws-game
